= 融宝用户版 Docs API 文档 1.0
作者 79277490@qq.com
v1.0, 2017-09-19
:toc: left
:toclevels: 3
:toc-title: 目  录
:doctype: book
:icons: font
:operation-curl-request-title: Curl 请求
:operation-httpie-request-title: HTTPie 请求
:operation-http-request-title: Http 请求
:operation-request-parameters-title: 请求参数说明
:operation-request-fields-title: 请求参数说明
:operation-http-response-title: Http 响应
:operation-response-fields-title: Http 响应字段说明
:operation-links-title: 相关链接

[[overview]]
== 1、概要
本文为API说明文档。

API的说明包括：请求方式、请求地址、请求参数说明和响应消息等。

服务器访问路径：http://192.168.3.254/

ContextPath: /consumer

资源文件访问根路径:http://192.168.3.254/static/

请求参数以数据库表字段驼峰命名(数据库表字段为大写,单词间以"_"连接）
例：数据库表字段 USER_ID ------> 参数名 userId

[[overview-response]]
== 2、通用说明

*通用请求参数说明*

默认请求body类型为：application/json; charset=utf-8;
所有请求头部必须携带如下参数

|===
| 字段 | 类型 | 解释

| hyAV
| String
| App版本

| hyCV
| String
| 客户端类型
|===

登录后头部还需要增加如下参数

|===
| 字段 | 类型 | 解释

| hyUI
| String
| 用户ID

| hyUP
| String
| 用户手机号

| hyUT
| String
| 访问令牌
|===

.请求主体参数规则:
 {"params":{单个实体相关参数},"datas":[多个实体对象],"reqData":{其它非实体对象参数包装}}

*非 hy API 通用响应消息说明*

|===
| 字段 | 类型 | 解释

| code
| int
| 0为成功，非0为失败

| data
| Object
| 请求后返回的数据

| msg
| String
| 响应附带的消息(通常为错误信息)
|===

[[resources-hy]]
== 3、用户模块

[[resources-hy-user]]
=== 3.1、用户注册登录

用户模块包含注册，登录，修改信息等针对用户进行CRUD的接口

[[resources-hy-user-add]]
==== 3.1.1、用户注册

operation::hy-user-add[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[resources-hy-user-sms]]
==== 3.1.2、获取短信验证码

获取的短信验证码在5分钟内将失效

operation::hy-user-sms[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[resources-hy-user-login]]
==== 3.1.3、用户登录

operation::hy-user-login[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[resources-hy-user]]
=== 3.2、用户实名认证

[[resources-hy-user-certS1]]
==== 3.2.1、认证第一步

operation::hy-user-certS1[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[resources-hy-user-certS2]]
==== 3.2.2、认证第二步

operation::hy-user-certS2[snippets='curl-request,http-request,request-fields,http-response,response-fields,links']

[[resources-hy-user-certS3]]
==== 3.2.3、认证第三步

operation::hy-user-certS3[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[resources-hy-user-certS4]]
==== 3.2.4、认证第四步

operation::hy-user-certS4[snippets='curl-request,http-request,request-fields,http-response,response-fields']

[[resources-hy-user-find-name]]
==== 3.2.6、User 姓名查找（支持模糊查找）

operation::hy-user-find-name[snippets='curl-request,http-request,request-parameters,http-response']

[[resources-hy-user-delete]]
==== 3.2.7、User 删除

operation::hy-user-delete[snippets='curl-request,http-request,http-response']

[[resources-hy-company]]
=== 3.3、Company

[[resources-hy-company-profile]]
==== 3.3.1、Company 接口信息描述

operation::hy-company-profile[snippets='curl-request,http-request,http-response,response-fields']

[[resources-hy-company-add]]
==== 3.3.3、Company 添加

operation::hy-company-add[snippets='curl-request,http-request,request-fields,http-response']

[[resource-hy-other]]
=== 9、其它接口


[[resources-hy-company-index]]
==== 3.3.2、Company 列表

operation::hy-company-list[snippets='curl-request,http-request,request-fields,http-response,response-fields,links']